### ISSUE TITLE
FFaudioConverter icon is wrong on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [Bleuzen/FFaudioConverter#1]
Hi

I use FFaudioConverter on Arch Linux running KDE Plasma Wayland session.
As we can see in the screenshot below, the title bar shows a Wayland generic icon instead
FFaudioConverter icon. FFaudioConverter icon is also wrong in the task switcher (alt+tab).

![ffaudioconverter](https://user-images.githubusercontent.com/15967631/52522691-dd75fd00-2c6f-11e9-9a2f-e64e4066a986.png)

**Comment by Bleuzen** [comment]
Thanks for reporting. It should be fixed by the latest commit
https://github.com/Bleuzen/FFaudioConverter/commit/e66c2902f37c9b4b22ad64e81df27e242c47425e

Can you test latest master?

**Comment by glaubersm** [comment]
Unfortunately I don't know how to compile source code. :(

**Comment by Bleuzen** [comment]
Ok, here is a binary compiled from latest master.
[ffaudioconverter-waylandicontest1.tar.gz](https://github.com/Bleuzen/FFaudioConverter/files/2848235/ffaudioconverter-waylandicontest1.tar.gz)

**Comment by glaubersm** [comment]
Thanks.  I can confirm that the bug is fixed with your binary.

**Comment by Bleuzen** [comment]
Ok great, so it will be fixed in next release :)
