### ISSUE TITLE
text field and spinbox are borderless

### ISSUE THREAD

**Issue by glaubersm** [Bleuzen/FFaudioConverter#2]
Hi
I installed your software on Arch Linux (from AUR) running KDE Plasma DE.
As we can see in the screenshot below, "FFmped binary" field and "Threads" spinbox look borderless. FFaudioConverter is the only Qt app on my system with such appearance.

![ffaudioconverter](https://user-images.githubusercontent.com/15967631/72808556-942c7c80-3c38-11ea-8cd4-34e41b3a6cc4.png)

**Comment by Bleuzen** [comment]
Hi, thanks for reporting.

I tried it myself and found out that this only happens with the Brezze themes.
Here is an example of what it looks like with the Materia theme:

![grafik](https://user-images.githubusercontent.com/12885163/72904578-6bd37980-3d2f-11ea-8fd9-fee7a95f902b.png)

As you can see, there is some kind of border (underline in this theme).

What FFaudioConverter currently is doing, is it just lets the system theme decide on what things should look like and what border they have.
I like this behavior and don't really want to change this.

The Breeze theme just seems to have no border for QLineEdit elements. Not sure if this is a design decission of them or a bug. Maybe you can report an issue there.


As of what other apps are doing:
There are multiple elements in Qt for taking user input. QLineEdit is only one of them.
I did some more testing with the Breeze theme and other user text input elements do have a border with this theme. I guess the other apps you are using are just using other Qt elements, thats why you see this borderless input only in FFaudioConverter.

Just to make sure:
Please try it with a different theme (not Breeze and nothing Breeze based) and send a screenshot again.

**Comment by glaubersm** [comment]
humm, here is my screenshot with Materia kvantum.

![materia kvantum](https://user-images.githubusercontent.com/15967631/72910752-bf39cd80-3d17-11ea-9a6f-89847ce27121.png)

**Comment by Bleuzen** [comment]
Yep, seems to be a bug or design choice of the Breeze theme.
Not a bug of FFaudioConverter.
