### ISSUE TITLE
Can't add multiple individual files from the command line

### ISSUE THREAD

**Issue by fabertawe** [Bleuzen/FFaudioConverter#3]
OS: Arch Linux; FFaudioConverter v0.27

Hello! Thanks for the software but I'm having a frustrating problem.

I can use "path" from the command line to add a folder or a single file to the queue to be processed but I can't add multiple files.

I need this functionality for use within my file manager - SpaceFM. I can pass a selection of files but I can't find a way for FFaudioConverter to accept more than the first file. I also don't want to pass a whole folder as I normally work on selected files from within a folder.

Please could you consider adding this functionality, many thanks.

**Comment by Bleuzen** [comment]
Hi, this should be fixed now :D
Please update to v0.28 and report back if it works for you.

**Comment by fabertawe** [comment]
> Hi, this should be fixed now :D
> Please update to v0.28 and report back if it works for you.

Yes, all working. Excellent! Many thanks.
