### ISSUE TITLE
More audio quality options

### ISSUE THREAD

**Issue by ppnplus** [Bleuzen/FFaudioConverter#7]
I'd like the program to have more audio quality options. For example, Ogg Vorbis currently have steps increasing in 2 or 64kbps (VBR Q0, 2, 4, 6, 8 or CBR 64, 128, 192, 256, 320kbps). I wish I have more options, like for Q1, 3, 5, 7 and beyond.

This could be available either as the drop-down menu (as we currently have) or the slider.

**Comment by Bleuzen** [comment]
I added more quality options in https://github.com/Bleuzen/FFaudioConverter/commit/740d43e68d220c6e23c31fe93a3d1dadd7a63c6e
will be in next release :)

**Comment by Bleuzen** [comment]
@ppnplus New version is now released to Flathub and AUR
