### ISSUE TITLE
Installing on Mac?

### ISSUE THREAD

**Issue by samstone19943** [Bleuzen/FFaudioConverter#9]
How can I install this on Mac? Possibly include instructions for building from source if you don't feel like making another package (assuming it is possible in the current state of the code).

**Comment by fracturedprism** [comment]
Have a look at my PR #13

**Comment by Bleuzen** [comment]
Hi @samstone19943 you can have a look at the PR @fracturedprism linked above and try these commands to build from source

However you are on your own with that since there is no official Mac support (not planned in the foreseeable future) and I can't test it

Good luck
